export * from 'extension-tester-page-objects';
export * from 'selenium-webdriver';

export {
    CheBrowser,
    DashboardTestRunner,
    WorkspaceTestRunner,
    ActionsControl,
    ActivityBar,
    ViewControl,
    BottomBarPanel,
    DebugConsoleView,
    OutputView,
    TerminalView,
    TextView,
    DialogHandler,
    ModalDialog,
    OpenDialog,
    ContentAssist,
    ContentAssistItem,
    Editor,
    EditorGroup,
    EditorTab,
    EditorView,
    FileType,
    TextEditor,
    ContextMenu,
    ContextMenuItem,
    Menu,
    MenuItem,
    TitleBar,
    TitleBarItem,
    WindowControls,
    SideBarView,
    TitleActionButton,
    ViewContent,
    ViewItem,
    ViewPanelAction,
    ViewSection,
    ViewTitlePart,
    CustomTreeItem,
    CustomTreeSection,
    DefaultTreeItem,
    DefaultTreeSection,
    DialogTree,
    StatusBar,
    Workbench,
    Notification,
    NotificationCenter,
    Input,
    InputBox,
    QuickPickItem,
    Authenticator,
    OpenShiftAuthenticator,
    OpenShiftAuthenticatorMethod,
    CheDistribution
} from './module';
